import type { Influencer, Review, TrustMetrics, NetworkGraphData } from './types';

export const mockInfluencers: Influencer[] = [
  {
    id: 'mrbeast',
    name: 'MrBeast',
    platform: 'YouTube',
    followerCount: 234000000,
    verified: true,
    trustScore: 96,
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    bio: 'YouTuber known for extreme challenges, philanthropy, and viral content',
    trendingScore: 15420,
    timeline: [
      {
        id: 't1',
        date: '2012-02-19',
        type: 'video',
        title: 'Channel Launch',
        description: 'Started YouTube channel at age 13',
        platform: 'YouTube',
      },
      {
        id: 't2',
        date: '2017-01-01',
        type: 'video',
        title: 'Counting to 100,000',
        description: 'Gained initial viral attention by counting to 100,000',
        platform: 'YouTube',
        views: 20000000,
      },
      {
        id: 't3',
        date: '2018-06-15',
        type: 'video',
        title: 'I Gave My 40,000,000th Subscriber 40 Cars',
        description: 'Started large-scale giveaway videos',
        platform: 'YouTube',
        views: 50000000,
      },
      {
        id: 't4',
        date: '2019-10-25',
        type: 'achievement',
        title: 'Team Trees Campaign',
        description: 'Launched #TeamTrees with Mark Rober, raising $20M to plant 20M trees',
        platform: 'YouTube',
      },
      {
        id: 't5',
        date: '2020-05-01',
        type: 'video',
        title: 'I Opened A Restaurant That Pays You To Eat At It',
        description: 'Created elaborate challenge videos with huge budgets',
        platform: 'YouTube',
        views: 75000000,
      },
      {
        id: 't6',
        date: '2020-12-01',
        type: 'achievement',
        title: 'MrBeast Burger Launch',
        description: 'Launched virtual restaurant brand MrBeast Burger',
        platform: 'Business',
      },
      {
        id: 't7',
        date: '2021-03-01',
        type: 'video',
        title: 'Squid Game In Real Life!',
        description: 'Recreated Squid Game with $456,000 prize',
        platform: 'YouTube',
        views: 456000000,
      },
      {
        id: 't8',
        date: '2022-01-29',
        type: 'achievement',
        title: 'Feastables Chocolate Launch',
        description: 'Launched Feastables chocolate brand',
        platform: 'Business',
      },
      {
        id: 't9',
        date: '2022-03-15',
        type: 'video',
        title: '1,000 Blind People See For The First Time',
        description: 'Funded cataract surgeries for 1,000 people',
        platform: 'YouTube',
        views: 125000000,
      },
      {
        id: 't10',
        date: '2023-11-04',
        type: 'achievement',
        title: 'Became Most Subscribed YouTuber',
        description: 'Surpassed 200M subscribers, becoming most subscribed individual creator',
        platform: 'YouTube',
      },
    ],
  },
  {
    id: '1',
    name: 'Sarah Johnson',
    platform: 'Instagram',
    followerCount: 1200000,
    verified: true,
    trustScore: 87,
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
    bio: 'Fitness & wellness coach. Helping you live your best life!',
  },
  {
    id: '2',
    name: 'Mike Chen',
    platform: 'YouTube',
    followerCount: 850000,
    verified: true,
    trustScore: 92,
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    bio: 'Tech reviews and tutorials. Honest opinions only.',
    trendingScore: 8930,
  },
  {
    id: '3',
    name: 'Emma Davis',
    platform: 'TikTok',
    followerCount: 2500000,
    verified: true,
    trustScore: 78,
    avatarUrl: 'https://i.pravatar.cc/150?img=5',
    bio: 'Fashion & lifestyle content creator',
    trendingScore: 12150,
  },
  {
    id: '4',
    name: 'Alex Rivera',
    platform: 'Instagram',
    followerCount: 450000,
    verified: false,
    trustScore: 65,
    avatarUrl: 'https://i.pravatar.cc/150?img=8',
    bio: 'Travel blogger exploring the world',
  },
  {
    id: '5',
    name: 'Jessica Lee',
    platform: 'YouTube',
    followerCount: 1800000,
    verified: true,
    trustScore: 95,
    avatarUrl: 'https://i.pravatar.cc/150?img=9',
    bio: 'Beauty & skincare expert. Science-based recommendations.',
  },
];

export const mockReviews: Record<string, Review[]> = {
  'mrbeast': [
    {
      id: 'rmb1',
      userId: 'umb1',
      userName: 'Chris P.',
      rating: 5,
      comment: 'Got a MrBeast Burger and it was amazing! Plus his videos are always entertaining and genuine.',
      productName: 'MrBeast Burger',
      date: '2025-11-14',
      verified: true,
    },
    {
      id: 'rmb2',
      userId: 'umb2',
      userName: 'Rachel M.',
      rating: 5,
      comment: 'His philanthropy work is incredible. Actually helps people instead of just talking about it.',
      date: '2025-11-13',
      verified: true,
    },
    {
      id: 'rmb3',
      userId: 'umb3',
      userName: 'Kevin L.',
      rating: 5,
      comment: 'Feastables chocolate is genuinely good. Not just influencer merch.',
      productName: 'Feastables Chocolate',
      date: '2025-11-12',
      verified: true,
    },
    {
      id: 'rmb4',
      userId: 'umb4',
      userName: 'Samantha R.',
      rating: 5,
      comment: 'Most trustworthy creator on YouTube. Always delivers on his promises.',
      date: '2025-11-10',
      verified: true,
    },
  ],
  '1': [
    {
      id: 'r1',
      userId: 'u1',
      userName: 'John D.',
      rating: 5,
      comment: 'Bought the protein powder she recommended. Great quality and actually works!',
      productName: 'Premium Whey Protein',
      date: '2025-11-10',
      verified: true,
    },
    {
      id: 'r2',
      userId: 'u2',
      userName: 'Maria S.',
      rating: 4,
      comment: 'Her workout plans are solid. Lost 10 pounds in 2 months!',
      date: '2025-11-08',
      verified: true,
    },
    {
      id: 'r3',
      userId: 'u3',
      userName: 'Tom R.',
      rating: 3,
      comment: 'Good content but some products are overpriced.',
      productName: 'Yoga Mat Pro',
      date: '2025-11-05',
      verified: true,
    },
  ],
  '2': [
    {
      id: 'r4',
      userId: 'u4',
      userName: 'Lisa M.',
      rating: 5,
      comment: 'Most honest tech reviewer on YouTube. Helped me choose the perfect laptop.',
      productName: 'Dell XPS 15',
      date: '2025-11-12',
      verified: true,
    },
    {
      id: 'r5',
      userId: 'u5',
      userName: 'David K.',
      rating: 5,
      comment: 'Always transparent about sponsorships. Very trustworthy.',
      date: '2025-11-09',
      verified: true,
    },
  ],
  '3': [
    {
      id: 'r6',
      userId: 'u6',
      userName: 'Sophie B.',
      rating: 4,
      comment: 'Love her style! Bought the dress she wore and it looks amazing.',
      productName: 'Summer Floral Dress',
      date: '2025-11-11',
      verified: true,
    },
    {
      id: 'r7',
      userId: 'u7',
      userName: 'Amy L.',
      rating: 2,
      comment: 'Some products don\'t match her claims. Be careful.',
      date: '2025-11-07',
      verified: false,
    },
  ],
};

export const mockTrustMetrics: Record<string, TrustMetrics> = {
  'mrbeast': {
    overallScore: 96,
    authenticity: 98,
    productQuality: 94,
    transparency: 97,
    engagement: 95,
  },
  '1': {
    overallScore: 87,
    authenticity: 90,
    productQuality: 85,
    transparency: 88,
    engagement: 85,
  },
  '2': {
    overallScore: 92,
    authenticity: 95,
    productQuality: 93,
    transparency: 94,
    engagement: 88,
  },
  '3': {
    overallScore: 78,
    authenticity: 80,
    productQuality: 75,
    transparency: 76,
    engagement: 82,
  },
};

export const mockNetworkData: Record<string, NetworkGraphData> = {
  '1': {
    nodes: [
      { id: '1', name: 'Sarah Johnson', val: 30, color: '#3b82f6' },
      { id: 'c1', name: 'Mike Chen', val: 20, color: '#10b981' },
      { id: 'c2', name: 'Emma Davis', val: 15, color: '#10b981' },
      { id: 'c3', name: 'Trainer Bob', val: 10, color: '#8b5cf6' },
      { id: 'c4', name: 'Nutritionist Amy', val: 12, color: '#8b5cf6' },
      { id: 'c5', name: 'Brand X', val: 8, color: '#f59e0b' },
    ],
    links: [
      { source: '1', target: 'c1', value: 5 },
      { source: '1', target: 'c2', value: 4 },
      { source: '1', target: 'c3', value: 8 },
      { source: '1', target: 'c4', value: 7 },
      { source: '1', target: 'c5', value: 3 },
      { source: 'c1', target: 'c2', value: 2 },
    ],
  },
  '2': {
    nodes: [
      { id: '2', name: 'Mike Chen', val: 30, color: '#3b82f6' },
      { id: 'c1', name: 'Sarah Johnson', val: 15, color: '#10b981' },
      { id: 'c2', name: 'Tech Reviewer A', val: 18, color: '#10b981' },
      { id: 'c3', name: 'Tech Reviewer B', val: 16, color: '#10b981' },
      { id: 'c4', name: 'Dell', val: 10, color: '#f59e0b' },
      { id: 'c5', name: 'Apple', val: 12, color: '#f59e0b' },
    ],
    links: [
      { source: '2', target: 'c1', value: 4 },
      { source: '2', target: 'c2', value: 7 },
      { source: '2', target: 'c3', value: 6 },
      { source: '2', target: 'c4', value: 5 },
      { source: '2', target: 'c5', value: 6 },
    ],
  },
};
